[package]
name = "y4m-codec"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "y4m-encoder"
path = "src/encoder.rs"

[[bin]]
name = "y4m-decoder"
path = "src/decoder.rs"

[dependencies.tokio]
version = "1.28.2"
features = ["rt", "rt-multi-thread", "macros", "sync"]

[dependencies.remotia]
path = "../../remotia/crates/remotia"
features = ["buffers"]

[dependencies.remotia-ffmpeg-codecs]
path = "../../remotia-ffmpeg-codecs"

[dependencies]
async-trait = "0.1.68"
clap = { version = "4.5", features = ["derive"] }
cstr = "0.2"
env_logger = "0.10.0"
png = "0.18"
log = "0.4.27"
rsmpeg = { git = "https://github.com/aegroto/rsmpeg", branch = "fix/updated_rusty_api", default-features = false, features = ["ffmpeg7_1", "link_vcpkg_ffmpeg"] }
y4m = "0.8.0"

[profile.release]
opt-level = 3
lto = true

[package.metadata.vcpkg]
dependencies = ["ffmpeg[x264]:x64-linux"]
git = "https://github.com/microsoft/vcpkg"
rev = "34823ada10"
