[package]
name = "screen-recorder"
version = "0.1.0"
edition = "2024"

[dependencies.tokio]
version = "1.44.2"
features = ["rt-multi-thread"]

[dependencies.remotia]
version = "0.1.0"
features = ["capture", "buffers"]
