[package]
name = "screen-stream"
version = "0.1.0"
edition = "2021"

[package.metadata.vcpkg]
dependencies = [
    # "llvm:x64-windows-static-md",
    # "ffmpeg[x264,vpx]:x64-windows-static-md",
    "ffmpeg[x264]",
]
git = "https://github.com/microsoft/vcpkg"
rev = "5a58e645cefaae63d149ff50fc1ca1ec54c47a77"

[dependencies.tokio]
version = "1.28.2"
features = ["rt", "rt-multi-thread", "macros", "net"]

[dependencies.remotia]
# version = "0.1.3"
path = "../../remotia/crates/remotia"
features = ["buffers", "capture", "render", "profilation", "serialization"]

[dependencies.remotia-ffmpeg-codecs]
path = "../../remotia-ffmpeg-codecs"
# git = "https://github.com/remotia/remotia-ffmpeg-codecs"
# branch = "flushing_improvements"

[dependencies.remotia-srt]
path = "../../remotia-srt"
# git = "https://github.com/remotia/remotia-srt"
# branch = "master"

[dependencies]
log = "0.4.19"
env_logger = "0.10.0"
bitcode = "0.6.7"
clap = "4.3.3"
async-trait = "0.1.89"
image = "0.25.8"
scap = "0.0.8"
